
  export const Number = [
        {
          men_title: "T-shirt",
          men_price: "599",
          women_title: "Dress-1",
          women_price: "599",
          kid_title: "Kurta-1",
          kid_price: "699",
        },
        {
          men_title: "T-shirt-2",
          men_price: "549",
          women_title: "Dress-2",
          women_price: "599",
          kid_title: "Kurta-2",
          kid_price: "699",
        },
        {
          men_title: "T-shirt-3",
          men_price: "199",
          women_title: "Dress-3",
          women_price: "599",
          kid_title: "Kurta-3",
          kid_price: "699",
        },
        {
          men_title: "T-shirt-4",
          men_price: "399",
          women_title: "Dress-4",
          women_price: "599",
          kid_title: "Kurta-4",
          kid_price: "699",
        },
        {
          men_title: "T-shirt-5",
          men_price: "299",
          women_title: "Dress-5",
          women_price: "599",
          kid_title: "Kurta-5",
          kid_price: "699",
        },
        {
          men_title: "T-shirt-6",
          men_price: "299",
          women_title: "Dress-5",
          women_price: "599",
          kid_title: "Kurta-5",
          kid_price: "699",
        },
        {
          men_title: "T-shirt-7",
          men_price: "299",
          women_title: "Dress-5",
          women_price: "599",
          kid_title: "Kurta-5",
          kid_price: "699",
        },
        {
          men_title: "T-shirt-8",
          men_price: "299",
          women_title: "Dress-5",
          women_price: "599",
          kid_title: "Kurta-5",
          kid_price: "699",
        },
        {
          men_title: "T-shirt-9",
          men_price: "299",
          women_title: "Dress-5",
          women_price: "599",
          kid_title: "Kurta-5",
          kid_price: "699",
        },
        {
          men_title: "T-shirt-10",
          men_price: "299",
          women_title: "Dress-5",
          women_price: "599",
          kid_title: "Kurta-5",
          kid_price: "699",
        },
      ];

        